apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "workitem-automate.fullname" . }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: workitem-automate
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              envFrom:
                - secretRef:
                    name: {{ include "workitem-automate.fullname" . }}-secret
              resources:
                {{- toYaml .Values.resources | nindent 16 }}