apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workitem-automate.fullname" . }}-secret
type: Opaque
stringData:
  CLIENT_ID: "{{ .Values.env.CLIENT_ID }}"
  CLIENT_SECRET: "{{ .Values.env.CLIENT_SECRET }}"
  REFRESH_TOKEN: "{{ .Values.env.REFRESH_TOKEN }}"
  AZURE_ORG: "{{ .Values.env.AZURE_ORG }}"
  AZURE_PROJECT: "{{ .Values.env.AZURE_PROJECT }}"
  AZURE_PAT: "{{ .Values.env.AZURE_PAT }}"
  GMAIL_SUBJECT: "{{ .Values.env.GMAIL_SUBJECT }}"
  GMAIL_FROM: "{{ .Values.env.GMAIL_FROM }}"
  AREA_PATH: "{{ .Values.env.AREA_PATH }}"
  ITERATION_PATH: "{{ .Values.env.ITERATION_PATH }}"
  TEAMS_WEBHOOK_URL: "{{ .Values.env.TEAMS_WEBHOOK_URL }}"
  PARENT_TASK: "{{ .Values.env.PARENT_TASK }}"